global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'fit-coach-app'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['fit-coach-app:8080']

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
