spring:
  application:
    name: gateway
  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: report-route # Unique id of the route
          uri: lb://report  # Reports microservice
          predicates:
            - Path=/api/v1/report/**

        - id: fit-coach-route # route id for services
          uri: lb://fit-coach # Fit coach microservice
          predicates:
            - Path=/api/v1/fit-coach/**

        - id: fit-coach-swagger
          uri: lb://fit-coach # Fit coach microservice
          predicates:
            - Path=/swagger-ui/**, /v3/api-docs/**, /swagger-resources/**

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

server:
  port: 8765
