spring:
  application:
    name: gateway
  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: report-route # Unique id of the route
          uri: lb://report  # Use the service name from Eureka, 'lb' stands for load balancing.
          predicates: # condition that you want to check before routing to the given URI.
            - Path=/report/** # Path predicate for URI path matching

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

server:
  port: 8765
