spring:
  application:
    name: gateway
  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: fit-coach-security
          uri: lb://security  # security microservice
          predicates:
              - Path=/api/v1/fit-coach/auth/**

        - id: report-service
          uri: lb://report  # report microservice
          predicates:
            - Path=/api/v1/fit-coach/report/**

        - id: fit-coach-route
          uri: lb://fit-coach # fit-coach microservice
          predicates:
            - Path=/api/v1/fit-coach/trainees/**, /api/v1/fit-coach/trainers/**, /api/v1/fit-coach/trainings/**, /api/v1/fit-coach/training-types/**

        - id: fit-coach-swagger
          uri: lb://fit-coach # fit-coach microservice
          predicates:
            - Path=/swagger-ui/**, /v3/api-docs/**, /swagger-resources/**

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

server:
  port: 8765

token:
  signing:
    key: SW1hZ2luYXRpb24gaXMgbW9yZSBpbXBvcnRhbnQgdGhhbiBrbm93bGVkZ2Uu

logging:
  level:
    root: INFO
  pattern:
    config: /logback-spring.xml
