spring.application.name: fit-coach

spring:
  profiles:
    active: local

server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
