spring:
  application.name: security

  datasource:
    url: jdbc:mysql://localhost:3306/fit_coach_users?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    close-timeout: 15000
    in-memory: false
    pool:
      enabled: true
      max-connections: 5
    packages:
      trust-all: true

token:
  signing:
    key: SW1hZ2luYXRpb24gaXMgbW9yZSBpbXBvcnRhbnQgdGhhbiBrbm93bGVkZ2Uu

server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
