spring:

  data:
    mongodb:
      database: report
      uri.mongodb: //localhost:27017/report
      auto-index-creation: true

  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    packages:
      trust-all: true
    listener:
      consumer:
        retry:
          delay: 1000  # Delay between retries in milliseconds
          enabled: true
          max-attempts: 3
      queues:
        training-session-queue: "training.session"
        dead-letter-queue: "training.session.DLQ"
